services:
  postgres-app:
    image: postgres:alpine
    container_name: ximaoxinho
    restart: unless-stopped
    env_file:
      - .postgres_app.env
    volumes:
      - postgres-app-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U matheus -d simao_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    image: maven:3.9-eclipse-temurin-25
    container_name: simao-app
    working_dir: /app
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    env_file:
      - .app_env
    command: >
      mvn spring-boot:run
      -Dspring-boot.run.jvmArguments="
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:5005:5005"
    depends_on:
      postgres-app:
        condition: service_healthy

volumes:
  postgres-app-data:
