version: '3.8'

services:
  mongodb:
    image: mongo:8.0
    container_name: sansaodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: sansaoadmin
    volumes:
      - mongo-data:/data/db
    networks:
      - sansao-net

  sansao-api:
    image: sansao-api:latest
    container_name: sansao-api
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=sansaodb
      - SPRING_DATA_MONGODB_USERNAME=sansaouser
      - SPRING_DATA_MONGODB_PASSWORD=sansaouser
      - BOT_NAME=YourBotName
      - BOT_TOKEN=YourBotToken
    networks:
      - sansao-net

volumes:
  mongo-data:

networks:
  sansao-net:
    driver: bridge
