GRANT ALL PRIVILEGES ON DATABASE simaodb TO matheus;
GRANT ALL ON SCHEMA public TO matheus;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO matheus;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO matheus;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO matheus;